### PR TITLE
Enable UI manipulation

### PR DESCRIPTION
**Pull request by sachanacar**
The only drawback of this application was that the editor was always 'lying on top' of the preview which meant that anything requiring clicks would not work.

Fix:
- Add document.getElementById('editor').style.display ="none"; to toggle() function so the editor disappears when in preview mode
- Add z-index: 9999 to toolbar so it always stays there on top of both elements

### CODE REVIEW

**Comment by mrdoob** [comment]
Do you have a code example that I can use as reference to try other solutions?

**Comment by sachanacar** [comment]
Sorry must have missed that!

All of these changes are reflected in the following app: https://developers.voxbone.com/webrtc-editor/

As you can see I can manipulate the UI (eg, add input, click buttons, etc..)

**Comment by mrdoob** [comment]
#14

**Comment by sachanacar** [comment]
😢

**Comment by mrdoob** [comment]
Oh?

**Pull request closed without merging**
